name:                sat-solver-hs
version:             0.1.0.0
github:              "GuilhemAllaman/sat-solver-hs"
license:             BSD3
author:              "Guilhem Allaman"
maintainer:          "guilhemallaman@hotmail.fr"
copyright:           "flwr-pwr"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/GuilhemAllaman/sat-solver-hs#readme>

dependencies:
- base >= 4.7 && < 5
- containers

library:
  source-dirs: src

executables:
  sat-solver-hs-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sat-solver-hs

tests:
  sat-solver-hs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sat-solver-hs
